### PR TITLE
Fix the mode parameter in appendAvailableDevices

### PR DESCRIPTION
**Pull request by thilinarmtb**
We were getting an error when calling `occa::getDeviceList()`. It printed out an error saying
mode is not defined. So we made these changes. But still, `mode = OpenCL` and `mode = CUDA`
fails. `mode = Serial` works.

### CODE REVIEW

**Comment by dmed256** [comment]
oh, @tcew just pinged me about it and I added a hack fix
This is only an issue in 0.1 (master branch), I'll add the same method for 1.0 soon

**Comment by dmed256** [comment]
Oops, the OpenCL and CUDA versions don't use 
```
setup("mode = OpenCL", p, d);
setup("mode = CUDA", d);
```
Since it uses a really oooooold way of initializing the devices

**Comment by thilinarmtb** [comment]
I see. Thanks @dmed256.

**Comment by dmed256** [comment]
@thilinarmtb: np, thanks for the PR! I saw the email after I pushed the change, sorry about that :(

**Comment by thilinarmtb** [comment]
No problem at all. Thank you very much for the fix !!

**Pull request closed without merging**
