### PR TITLE
Add a function for stream to wait for a tag

### PR DESCRIPTION
**Pull request by deukhyun-cha**
This is to implement a feature described in Add support a stream to synchronize for a specific event #512.

### CODE REVIEW

**Comment by deukhyun-cha** [comment]
I would appreciate some help on testing especially for dpcpp and metal backends if possible.

**Comment by deukhyun-cha** [comment]
> I would appreciate some help on testing especially for dpcpp and metal backends if possible.

I was able to run the example added here for serial, cuda, dpcpp, and openmp backends.

**Comment by deukhyun-cha** [comment]
I was going through this change and feeling the interface should be done through the device like other stream related functions. If so, should it also work with current stream on the device (instead of taking the stream as an argument)? I would appreciate advice.

**Comment by kris-rowe** [comment]
> I was going through this change and feeling the interface should be done through the device like other stream related functions. If so, should it also work with current stream on the device (instead of taking the stream as an argument)? I would appreciate advice.

Since it is complete, I would leave the existing implementation in the PR as is.

There is already a [`waitFor` function in `device`](https://github.com/libocca/occa/blob/3cba0841b2b87678da53e0b311cb7e162d781181/include/occa/core/device.hpp#L482) that waits on a given `streamTag`. Since `streamTags` are associated with the `stream` which was active when they were created, the existing implementation of `device::waitFor` is problematic in the case where the active stream has been changed by the user. To avoid this ambiguity, `device::waitFor` should be reimplemented later using the function added in this PR to synchronize the current `stream`. A separate API for waiting on a specific `streamTag` could be added to that class afterwards, if needed.

**Comment by deukhyun-cha** [comment]
> > I was going through this change and feeling the interface should be done through the device like other stream related functions. If so, should it also work with current stream on the device (instead of taking the stream as an argument)? I would appreciate advice.
> 
> Since it is complete, I would leave the existing implementation in the PR as is.
> 
> There is already a [`waitFor` function in `device`](https://github.com/libocca/occa/blob/3cba0841b2b87678da53e0b311cb7e162d781181/include/occa/core/device.hpp#L482) that waits on a given `streamTag`. Since `streamTags` are associated with the `stream` which was active when they were created, the existing implementation of `device::waitFor` is problematic in the case where the active stream has been changed by the user. To avoid this ambiguity, `device::waitFor` should be reimplemented later using the function added in this PR to synchronize the current `stream`. A separate API for waiting on a specific `streamTag` could be added to that class afterwards, if needed.

Thanks @kris-rowe, appreciate your comment.

**Comment by deukhyun-cha** [comment]
I was able to build this for Metal backend and run stream examples (after updating for some fixes) on a Mac. The branch is update.

**Comment by deukhyun-cha** [comment]
@kris-rowe just wanted to check if you have any general comments for me to consider on this PR before the detailed review?

**Review by kris-rowe — APPROVED** [review]

**Pull request merged**
