### PR TITLE
HIP Backend for OCCA

### PR DESCRIPTION
**Pull request by noelchalmers**
### Description

This pull adds AMD's HIP as a backend in OCCA's parser. In large part the HIP backend is identical to the CUDA backend as HIP was designed to be able to convert standard CUDA functions in place. The notable difference is in kernel::run() wherein HIP only supports passing arguments to kernels via the last parameter when launching modules, i.e. by wrapping a pointer to a void * struct 
 and packing with HIP_LAUNCH_PARAM_BUFFER_POINTER, HIP_LAUNCH_PARAM_BUFFER_SIZE, and HIP_LAUNCH_PARAM_END.

Also included is a fix to a __local variable scoping issue when using AMD's OpenCL compiler. By default OCCA will parse an okl such as 

```cpp
@kernel void foo() {
    for(int i=0;i<100;i++;@outer0) {
        @shared float s_a[10];
         for(int j=0;j<10;j++;@inner0) {
             s_a[j]+=1;
         }
    }
}
```

into OpenCL source 

```cpp
__global void foo() {
    {
        __local float s_a[10];
         {
             s_a[j]+=1;
         }
    }
}
```

However, AMD's OpenCL compiler with complain that __local variables must be declared in the outermost scope of a kernel function. In this pull, in the openclParser::setupKernels() function I've added a call to a new migrateLocalDecls function which moves all __local variable declarations to the top of the kernel function which fixes this error. 

### Checks
- [x] Nothing got committed into `./lib` and `./obj`
- [x] MIT License copyright in new files

### CODE REVIEW

**Comment by dmed256** [comment]
@noelchalmers Briefly looked through it and it looks pretty good!
I'll take a closer look once I get home, thanks again!

**Comment by pdhahn** [comment]
I am concerned about the part that lifts _local variables. Are they actually being moved into host address space (inside the @kernel but outside the @outer nested kernel)?

**Comment by noelchalmers** [comment]
@pdhahn I'm not sure I follow. In OpenCL mode, the __local variables are moved after kernels are split to directly after a statement like __global foo() {  so that they are in the outermost scope of the kernel. Can you clarify what you mean about the host address space?

**Comment by pdhahn** [comment]
Also, I am using NVIdia GPUs with OCCA/OpenCL, so maybe your changes only apply to a problem that occurs when using AMD hardware?

**Comment by noelchalmers** [comment]
@pdhahn Yes I believe that's correct. In my experience only the AMD OpenCL compiler complains about this type of scoping issue. It could likely be fixed on that end, but this is sufficient work around and doesn't alter any kernel behavior.

**Comment by pdhahn** [comment]
Actually I corrected my comment to read migrate to "_global" instead of host address space. Is that what your code does?

**Comment by noelchalmers** [comment]
No I don't believe so. In my example above, the parsed source file simply changes from this:

```cpp
__global void foo() {
    {
        __local float s_a[10];
         {
             s_a[j]+=1;
         }
    }
}
```

to this:

```cpp
__global void foo() {
     __local float s_a[10];
    {
         {
             s_a[j]+=1;
         }
    }
}
```

**Comment by pdhahn** [comment]
Ah, got it. Thanks for the patient explanation..

**Comment by noelchalmers** [comment]
No worries. My apologies if my initial explanation was unclear. It's a strange issue that really shouldn't exist, but lucky a fix is straightforward.

**Comment by dmed256** [comment]
I put a few comments but overall it looks good, thanks a lot for adding this PR!

**Pull request merged**
