### PR TITLE
Fix compilation on macOS

### PR DESCRIPTION
**Pull request by Luthaf**
## Description

I tried to build occa on my computer (macOS Mojave 10.14.6), and hit a two small compilation errors, one on ObjectiveC code and one related to linking to the Metal framework. I tried to run tests locally, but got two errors, reproduced below. I can try to fix them, but I might need a bit of guidance on where to look at to understand the origin of the problem.

#### bin-functional-range
```
Subprocess aborted***Exception:   0.74 sec
~/occa/build/occa/cache/cd69f970aba1cc18/source.cpp:16:45: error: cannot form a reference to 'void'
                                 const void & occa_range_end) {
                                            ^
1 error generated.

---[ Error ]--------------------------------------------------------------------
    File     : ~/occa/src/occa/internal/modes/serial/device.cpp
    Line     : 367
    Function : buildKernel
    Message  : Error compiling [_occa_jit_kernel], Command: [g++ -O3 -std=c++11 -fPIC -shared ~/occa/build/occa/cache/cd69f970aba1cc18/source.cpp -o ~/occa/build/occa/cache/cd69f970aba1cc18/binary -I~/occa/include -I~/occa/build/include -L~/occa/build/lib -locca]
    Stack
      3 range               main
      2 libdyld.dylib       start
      1 ???                 0x0
================================================================================

libc++abi.dylib: terminating with uncaught exception of type occa::exception:
---[ Error ]--------------------------------------------------------------------
    File     : ~/occa/tests/src/functional/range.cpp
    Line     : 102
    Function : testEvery
    Message  : Assertion Failed: Value not true
    Stack
      4 range               testEvery()
      3 range               main
      2 libdyld.dylib       start
      1 ???                 0x0
================================================================================
```

####  bin-loops-forLoop 
```
Subprocess aborted***Exception:   0.74 sec
[CUDA] mode is not enabled, defaulting to [Serial] mode
[HIP] mode is not enabled, defaulting to [Serial] mode
~/occa/build/occa/cache/f97fbaef8bd8bfe5/source.cpp:16:45: error: cannot form a reference to 'void'
                                 const void & occa_range_end,
                                            ^
1 error generated.
libc++abi.dylib: terminating with uncaught exception of type occa::exception:
---[ Error ]--------------------------------------------------------------------
    File     : ~/occa/src/occa/internal/modes/serial/device.cpp
    Line     : 367
    Function : buildKernel
    Message  : Error compiling [_occa_jit_kernel], Command: [g++ -O3 -std=c++11 -fPIC -shared ~/occa/build/occa/cache/f97fbaef8bd8bfe5/source.cpp -o ~/occa/build/occa/cache/f97fbaef8bd8bfe5/binary -I~/occa/include -I~/occa/build/include -L~/occa/build/lib -locca]
    Stack
      13 libocca.dylib       occa::serial::device::buildKernel(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, occa::hash_t, occa::json const&, bool)
      12 libocca.dylib       occa::serial::device::buildKernel(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, occa::hash_t, occa::json const&)
      11 libocca.dylib       occa::device::buildKernel(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, occa::json const&) const
      10 libocca.dylib       occa::device::buildKernelFromString(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, occa::json const&) const
       9 libocca.dylib       occa::kernelBuilder::getOrBuildKernel(occa::scope const&)
       8 libocca.dylib       occa::kernelBuilder::run(occa::scope const&)
       7 libocca.dylib       occa::typelessArray::typelessMapTo(occa::memory, occa::baseFunction const&) const
       6 libocca.dylib       occa::memory occa::typelessArray::typelessMap<int>(occa::baseFunction const&) const
       5 libocca.dylib       occa::range::toArray() const
       4 forLoop             testOuterForLoops(occa::device)
       3 forLoop             main
       2 libdyld.dylib       start
       1 ???                 0x0
================================================================================

Testing mode: Serial
```

### CODE REVIEW

**Comment by Luthaf** [comment]
Additional info, I'm using cmake to build the code, while CI appears to be using the make build system.

**Review by dmed256 — APPROVED** [review]
If this fixes the Metal compilation issue, LGTM!

Thank you!!

**Comment by Luthaf** [comment]
This fix compiling the code, but the tests don't pass =/

**Comment by Luthaf** [comment]
I don't have the knowledge to fix the test failures described in the first comment, so I would appreciate a pointer to what could be going wrong here. I'm also happy with merging this as a first step (get it to compile) and try to tackle test failure later!

**Comment by dmed256** [comment]
Hi @Luthaf, sorry I've been extra busy these days. I'll see if I can replicate on my mac soon. Thank you for reaching out to try and get this fixed :pray:

**Comment by kris-rowe** [comment]
@Luthaf Is this issue resolved with the current version of the PR?

**Comment by Luthaf** [comment]
Yes, with the latest master merged, all tests now pass on my machine!

**Pull request merged**
