### PR TITLE
Make compiler_flags setting take precedence over the compiler flag env var

### LINKED ISSUE #621: `occa::json["compiler_flags"]` should override environment variable
e.g., https://github.com/libocca/occa/blob/2e576e69e07627a516b568079e047965a9bd8d24/src/occa/internal/modes/serial/device.cpp#L196

```

      if (compilerLanguageFlag == sys::language::CPP && env::var("OCCA_CXXFLAGS").size()) {
        compilerFlags = env::var("OCCA_CXXFLAGS");
      } else if (compilerLanguageFlag == sys::language::C && env::var("OCCA_CFLAGS").size()) {
        compilerFlags = env::var("OCCA_CFLAGS");
      } else if (kernelProps.get<std::string>("compiler_flags").size()) {
        compilerFlags = (std::string) kernelProps["compiler_flags"];
      } else if (compilerLanguageFlag == sys::language::CPP && env::var("CXXFLAGS").size()) {
        compilerFlags = env::var("CXXFLAGS");
      } else if (compilerLanguageFlag == sys::language::C && env::var("CFLAGS").size()) {
        compilerFlags = env::var("CFLAGS");
      } else {
#if (OCCA_OS & (OCCA_LINUX_OS | OCCA_MACOS_OS))
        compilerFlags = "-O3";
#else
        compilerFlags = " /Ox";
#endif
      }
```

Why is `OCCA_CXXFLAGS` used to set the compiler flags, despite `kernelProps["compiler_flags"]` being set?
I would have thought that setting the `kernelProps["compiler_flags]` should have taken precedence here.

### PR DESCRIPTION
**Pull request by MalachiTimothyPhillips**
Closes #621

### CODE REVIEW

**Review by kris-rowe — CHANGES_REQUESTED** [review]
For consistency, the flags for the SYCL backend should also be updated also.
https://github.com/libocca/occa/blob/2e576e69e07627a516b568079e047965a9bd8d24/src/occa/internal/modes/dpcpp/utils.cpp#L43

(Currently Metal and OpenMP don't have their own env variables for compiler flags).

**Comment by MalachiTimothyPhillips** [comment]
> For consistency, the flags for the SYCL backend should also be updated also.
> 
> https://github.com/libocca/occa/blob/2e576e69e07627a516b568079e047965a9bd8d24/src/occa/internal/modes/dpcpp/utils.cpp#L43
> 
> (Currently Metal and OpenMP don't have their own env variables for compiler flags).

Done.
If we go this route, we should also do #623 .

**Comment by kris-rowe** [comment]
@MalachiTimothyPhillips can you set your PR to merge into development.

**Comment by MalachiTimothyPhillips** [comment]
> @MalachiTimothyPhillips can you set your PR to merge into development.

Done. Please let me know if you need anything else. Cheers!

**Pull request merged**
