### PR TITLE
[Defines] Adding hypot function to the defines

### PR DESCRIPTION
**Pull request by jkozdon**
Adding hypot function to occa

### CODE REVIEW

**Comment by dmed256** [comment]
Looks good, thanks!

**Comment by jkozdon** [comment]
Perfect thanks!

**Comment by jkozdon** [comment]
BTW, I like that you have eliminated the python script as it simplifies the inclusion of new functionality.

**Comment by dmed256** [comment]
Thanks, it was pretty annoying

I would prefer to keep the source code in the .so but that didn't seem like
a good way to do it

I'll try to find a way to dump the source later, for now it's reading the
headers (also want to get rid of OCCA_DIR in the future)

**Pull request merged**
