### PR TITLE
[HIP] Support for new (ROCm 3.5+) HIP compiler and runtime

### PR DESCRIPTION
**Pull request by noelchalmers**
## Description

This PR adds supports for AMD's ROCm 3.5 HIP compiler (clang), and new ROCclr runtime. 

~~**This is a breaking change for all ROCm <3.5 installs.**~~

Back story: AMD's HIP was originally created as a thin interface layer which translated a CUDA-like API (i.e. HIP) into AMD's Heterogeneous Compute (HC) language. Source code was then compiled in HC with the hcc compiler. 

Rather than keeping HIP as just an interface layer, AMD added support for HIP as an actual language in the clang compiler (much like cuda-clang). The ROCm 3.5 release marks the transitioning to this new hip-clang compiler, and the deprecation of the HC language. 

https://github.com/RadeonOpenCompute/ROCm#Heterogeneous-Compute-Interface-for-Portability

### CODE REVIEW

**Comment by dmed256** [comment]
Awesome, I'll check this out soon!

**Comment by noelchalmers** [comment]
I should have added a description originally, but I'll note here that this is a breaking change for ROCm 3.3 or earlier. Maybe we can set a minor release tag before merging this so that people can grab the last version which supported ROCm 3.3?

**Comment by v-dobrev** [comment]
Is there no easy way to keep (at least for a while) this backward compatible? Maybe using some `#if ... #else ... #endif` blocks?

**Comment by noelchalmers** [comment]
It's possible, sure, but I'm not sure it's worth the effort. The hcc compiler and runtime have been marked as deprecating for a while, and I'm not of the opinion that it's worth carrying around support for it in OCCA anymore. But maybe @dmed256 has a different opinion. 

If we were to make a minor release like I'm suggesting, is there a case where ROCm 3.3 support would be needed that couldn't be solved by checking out that release tag?

**Comment by v-dobrev** [comment]
A hypothetical case is where there is a new bugfix/feature in OCCA (added after this PR is merged) that you need/want to use but the cluster you are running on does not have ROCm 3.5 yet.

If this involves some non-trivial amount of work, it's probably not worth it -- that's why I was asking about an "easy way" to keep backward compatibility.

**Comment by dmed256** [comment]
I'm seeing these as the main changes, let me know if I missed any other big ones:

#### Build

- Updates rocm location in shellTools (seems backwards compatible)
- Changes the linked library (`hip_hcc` &arr; `amdhip64`)

#### Runtime

- `-t gfx<arch>` &rarr; `--amdgpu-target=gfx<arch>`
- No `-locca`

---

@noelchalmers Can we use the library found to distinguish the ROCm compilation type?

#### Pseudocode
```
if library_found(amdhip64)
  OCCA_HIP_COMPILATION_TYPE = OCCA_HIP_ROCC_COMPILATION
elif library_found(hip_hcc) 
  OCCA_HIP_COMPILATION_TYPE = OCCA_HIP_HCC_COMPILATION
else
  OCCA_HIP_COMPILATION_TYPE = 0
endif
```

**Comment by noelchalmers** [comment]
Updated the PR branch to include backward compatibility with ROCm 3.3 and earlier. I've tested using separate ROCm 3.3 and 3.5 installs on OCCA's ctests as well as in larger projects like libparanumal.

**Pull request merged**
